/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package utente.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Utente service. Represents a row in the &quot;Utente_Utente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>utente.model.impl.UtenteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>utente.model.impl.UtenteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Utente
 * @generated
 */
@ProviderType
public interface UtenteModel
	extends BaseModel<Utente>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a utente model instance should use the {@link Utente} interface instead.
	 */

	/**
	 * Returns the primary key of this utente.
	 *
	 * @return the primary key of this utente
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this utente.
	 *
	 * @param primaryKey the primary key of this utente
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this utente.
	 *
	 * @return the uuid of this utente
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this utente.
	 *
	 * @param uuid the uuid of this utente
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the utente ID of this utente.
	 *
	 * @return the utente ID of this utente
	 */
	public long getUtenteId();

	/**
	 * Sets the utente ID of this utente.
	 *
	 * @param utenteId the utente ID of this utente
	 */
	public void setUtenteId(long utenteId);

	/**
	 * Returns the group ID of this utente.
	 *
	 * @return the group ID of this utente
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this utente.
	 *
	 * @param groupId the group ID of this utente
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this utente.
	 *
	 * @return the company ID of this utente
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this utente.
	 *
	 * @param companyId the company ID of this utente
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this utente.
	 *
	 * @return the user ID of this utente
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this utente.
	 *
	 * @param userId the user ID of this utente
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this utente.
	 *
	 * @return the user uuid of this utente
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this utente.
	 *
	 * @param userUuid the user uuid of this utente
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this utente.
	 *
	 * @return the user name of this utente
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this utente.
	 *
	 * @param userName the user name of this utente
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this utente.
	 *
	 * @return the create date of this utente
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this utente.
	 *
	 * @param createDate the create date of this utente
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this utente.
	 *
	 * @return the modified date of this utente
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this utente.
	 *
	 * @param modifiedDate the modified date of this utente
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this utente.
	 *
	 * @return the name of this utente
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this utente.
	 *
	 * @param name the name of this utente
	 */
	public void setName(String name);

	/**
	 * Returns the second name of this utente.
	 *
	 * @return the second name of this utente
	 */
	@AutoEscape
	public String getSecondName();

	/**
	 * Sets the second name of this utente.
	 *
	 * @param secondName the second name of this utente
	 */
	public void setSecondName(String secondName);

	/**
	 * Returns the codice fiscale of this utente.
	 *
	 * @return the codice fiscale of this utente
	 */
	@AutoEscape
	public String getCodiceFiscale();

	/**
	 * Sets the codice fiscale of this utente.
	 *
	 * @param codiceFiscale the codice fiscale of this utente
	 */
	public void setCodiceFiscale(String codiceFiscale);

	@Override
	public Utente cloneWithOriginalValues();

}